name = "TriangulateIO"
uuid = "2d5ea9ce-d22c-4cb0-a053-78efb41c0cf4"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.1.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinDeps = "^0.8.10"
DocStringExtensions = "^0.8.0"
julia = "1"
